package com.game.mancala.frame;

public enum GameState {
	
	START,PLAYER_1_TURN,PLAYER_2_TURN, 
	COLLECT_ALL_PLAYER_1, COLLECT_ALL_PLAYER_2, 
	COUNT_FOR_VERDICT, TRICK_MOVE_PLAYER_1, TRICK_MOVE_PLAYER_2,
	VALIDATE_GAME, END;
	

}
